version: '3.11.0'

services: 
  db:
    image: "keinos/sqlite3:latest"
    volumes:
      - sqlite_data:/data  # Cria um volume chamado sqlite_data para armazenar o banco de dados
    environment:
      - SQLITE_DATABASE=/data/backend_test.db  # Define o local do banco de dados dentro do contêiner
    command: echo "SQLite container running"  # Apenas um comando placeholder para manter o contêiner em execução

  docker-python:
    build:
      context: .
    ports:
      - "3000:5000"
    depends_on: 
      - db

volumes: 
  sqlite_data:  # Definição do volume sqlite_data
