version: '3.11.0'

services: 
  db:
    image: "keinos/sqlite3:latest"
    volumes:
      - sqlite_data:/data
    environment:
      - SQLITE_DATABASE=/data/backend_test.db
    command: echo "SQLite container running"

  docker-python:
    build:
      context: .
    ports:
      - "3000:5000"
    depends_on: 
      - db

volumes: 
  sqlite_data:
